# Generated by Django 5.1.15 on 2026-01-13 08:16

import access.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [

        migrations.CreateModel(
            name="GlpiImportProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="ID of the item",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("glpi_id", models.IntegerField(verbose_name="GLPI PK")),
                (
                    "glpi_model_name",
                    models.CharField(max_length=100, verbose_name="GLPI model_name"),
                ),
                (
                    "glpi_hash",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="GLPI model_name"
                    ),
                ),
                (
                    "created",
                    access.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Date and time of creation",
                        verbose_name="Created",
                    ),
                ),
            ],
            options={
                "unique_together": {("glpi_id", "glpi_model_name", "glpi_hash")},
            },
        ),
    ]
