from django.db import models

from .fields.zero_foriegnkwy import ZeroAsNoneForeignKey



class GlpiEntities(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    entities = ZeroAsNoneForeignKey( to = 'self', db_column = 'entities_id', related_name = 'child_entities' )
    completename = models.TextField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    level = models.IntegerField()
    sons_cache = models.TextField(blank=True, null=True)
    ancestors_cache = models.TextField(blank=True, null=True)
    registration_number = models.CharField(max_length=255, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    postcode = models.CharField(max_length=255, blank=True, null=True)
    town = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    website = models.CharField(max_length=255, blank=True, null=True)
    phonenumber = models.CharField(max_length=255, blank=True, null=True)
    fax = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    admin_email = models.CharField(max_length=255, blank=True, null=True)
    admin_email_name = models.CharField(max_length=255, blank=True, null=True)
    from_email = models.CharField(max_length=255, blank=True, null=True)
    from_email_name = models.CharField(max_length=255, blank=True, null=True)
    noreply_email = models.CharField(max_length=255, blank=True, null=True)
    noreply_email_name = models.CharField(max_length=255, blank=True, null=True)
    replyto_email = models.CharField(max_length=255, blank=True, null=True)
    replyto_email_name = models.CharField(max_length=255, blank=True, null=True)
    notification_subject_tag = models.CharField(max_length=255, blank=True, null=True)
    ldap_dn = models.CharField(max_length=255, blank=True, null=True)
    tag = models.CharField(max_length=255, blank=True, null=True)
    authldaps_id = models.PositiveIntegerField()
    mail_domain = models.CharField(max_length=255, blank=True, null=True)
    entity_ldapfilter = models.TextField(blank=True, null=True)
    mailing_signature = models.TextField(blank=True, null=True)
    url_base = models.TextField(blank=True, null=True)
    cartridges_alert_repeat = models.IntegerField()
    consumables_alert_repeat = models.IntegerField()
    use_licenses_alert = models.IntegerField()
    send_licenses_alert_before_delay = models.IntegerField()
    use_certificates_alert = models.IntegerField()
    send_certificates_alert_before_delay = models.IntegerField()
    certificates_alert_repeat_interval = models.IntegerField()
    use_contracts_alert = models.IntegerField()
    send_contracts_alert_before_delay = models.IntegerField()
    use_infocoms_alert = models.IntegerField()
    send_infocoms_alert_before_delay = models.IntegerField()
    use_reservations_alert = models.IntegerField()
    use_domains_alert = models.IntegerField()
    send_domains_alert_close_expiries_delay = models.IntegerField()
    send_domains_alert_expired_delay = models.IntegerField()
    autoclose_delay = models.IntegerField()
    autopurge_delay = models.IntegerField()
    notclosed_delay = models.IntegerField()
    calendars_strategy = models.IntegerField()
    calendars_id = models.PositiveIntegerField()
    auto_assign_mode = models.IntegerField()
    tickettype = models.IntegerField()
    max_closedate = models.DateTimeField(blank=True, null=True)
    inquest_config = models.IntegerField()
    inquest_rate = models.IntegerField()
    inquest_delay = models.IntegerField()
    inquest_url = models.CharField(db_column='inquest_URL', max_length=255, blank=True, null=True)  # Field name made lowercase.
    inquest_max_rate = models.IntegerField()
    inquest_default_rate = models.IntegerField()
    inquest_mandatory_comment = models.IntegerField()
    max_closedate_change = models.DateTimeField(blank=True, null=True)
    inquest_config_change = models.IntegerField()
    inquest_rate_change = models.IntegerField()
    inquest_delay_change = models.IntegerField()
    inquest_url_change = models.CharField(db_column='inquest_URL_change', max_length=255, blank=True, null=True)  # Field name made lowercase.
    inquest_max_rate_change = models.IntegerField()
    inquest_default_rate_change = models.IntegerField()
    inquest_mandatory_comment_change = models.IntegerField()
    autofill_warranty_date = models.CharField(max_length=255)
    autofill_use_date = models.CharField(max_length=255)
    autofill_buy_date = models.CharField(max_length=255)
    autofill_delivery_date = models.CharField(max_length=255)
    autofill_order_date = models.CharField(max_length=255)
    tickettemplates_strategy = models.IntegerField()
    tickettemplates_id = models.PositiveIntegerField()
    changetemplates_strategy = models.IntegerField()
    changetemplates_id = models.PositiveIntegerField()
    problemtemplates_strategy = models.IntegerField()
    problemtemplates_id = models.PositiveIntegerField()
    entities_strategy_software = models.IntegerField()
    entities_id_software = models.PositiveIntegerField()
    default_contract_alert = models.IntegerField()
    default_infocom_alert = models.IntegerField()
    default_cartridges_alarm_threshold = models.IntegerField()
    default_consumables_alarm_threshold = models.IntegerField()
    delay_send_emails = models.IntegerField()
    is_notif_enable_default = models.IntegerField()
    inquest_duration = models.IntegerField()
    inquest_duration_change = models.IntegerField()
    date_mod = models.DateTimeField(blank=True, null=True)
    date_creation = models.DateTimeField(blank=True, null=True)
    autofill_decommission_date = models.CharField(max_length=255)
    suppliers_as_private = models.IntegerField()
    anonymize_support_agents = models.IntegerField()
    display_users_initials = models.IntegerField()
    contracts_strategy_default = models.IntegerField()
    contracts_id_default = models.PositiveIntegerField()
    enable_custom_css = models.IntegerField()
    custom_css_code = models.TextField(blank=True, null=True)
    latitude = models.CharField(max_length=255, blank=True, null=True)
    longitude = models.CharField(max_length=255, blank=True, null=True)
    altitude = models.CharField(max_length=255, blank=True, null=True)
    transfers_strategy = models.IntegerField()
    transfers_id = models.PositiveIntegerField()
    agent_base_url = models.CharField(max_length=255, blank=True, null=True)
    approval_reminder_repeat_interval = models.IntegerField()
    is_contact_autoupdate = models.IntegerField()
    is_user_autoupdate = models.IntegerField()
    is_group_autoupdate = models.IntegerField()
    is_location_autoupdate = models.IntegerField()
    is_contact_autoclean = models.IntegerField()
    is_user_autoclean = models.IntegerField()
    is_group_autoclean = models.IntegerField()
    is_location_autoclean = models.IntegerField()
    state_autoupdate_mode = models.IntegerField()
    state_autoclean_mode = models.IntegerField()
    show_tickets_properties_on_helpdesk = models.IntegerField()
    custom_helpdesk_home_scene_left = models.CharField(max_length=255)
    custom_helpdesk_home_scene_right = models.CharField(max_length=255)
    custom_helpdesk_home_title = models.CharField(max_length=255)
    enable_helpdesk_home_search_bar = models.IntegerField()
    enable_helpdesk_service_catalog = models.IntegerField()
    expand_service_catalog = models.IntegerField()
    number_2fa_enforcement_strategy = models.IntegerField(db_column='2fa_enforcement_strategy')  # Field renamed because it wasn't a valid Python identifier.

    class Meta:
        managed = False
        app_label = "glpi_import"
        db_table = 'glpi_entities'
        unique_together = (('entities_id', 'name'),)
