from django.db import models

from .entities import GlpiEntities



class GlpiUsers(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)
    password_last_update = models.DateTimeField(blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    phone2 = models.CharField(max_length=255, blank=True, null=True)
    mobile = models.CharField(max_length=255, blank=True, null=True)
    realname = models.CharField(max_length=255, blank=True, null=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    locations_id = models.PositiveIntegerField()
    language = models.CharField(max_length=10, blank=True, null=True, db_comment='see define.php CFG_GLPI[language] array')
    use_mode = models.IntegerField()
    list_limit = models.IntegerField(blank=True, null=True)
    is_active = models.IntegerField()
    comment = models.TextField(blank=True, null=True)
    auths_id = models.PositiveIntegerField()
    authtype = models.IntegerField()
    last_login = models.DateTimeField(blank=True, null=True)
    date_mod = models.DateTimeField(blank=True, null=True)
    date_sync = models.DateTimeField(blank=True, null=True)
    is_deleted = models.IntegerField()
    profiles_id = models.PositiveIntegerField()
    entities_id = models.PositiveIntegerField(blank=True, null=True)
    usertitles_id = models.PositiveIntegerField()
    usercategories_id = models.PositiveIntegerField()
    date_format = models.IntegerField(blank=True, null=True)
    number_format = models.IntegerField(blank=True, null=True)
    names_format = models.IntegerField(blank=True, null=True)
    csv_delimiter = models.CharField(max_length=1, blank=True, null=True)
    is_ids_visible = models.IntegerField(blank=True, null=True)
    use_flat_dropdowntree = models.IntegerField(blank=True, null=True)
    use_flat_dropdowntree_on_search_result = models.IntegerField(blank=True, null=True)
    show_jobs_at_login = models.IntegerField(blank=True, null=True)
    priority_1 = models.CharField(max_length=20, blank=True, null=True)
    priority_2 = models.CharField(max_length=20, blank=True, null=True)
    priority_3 = models.CharField(max_length=20, blank=True, null=True)
    priority_4 = models.CharField(max_length=20, blank=True, null=True)
    priority_5 = models.CharField(max_length=20, blank=True, null=True)
    priority_6 = models.CharField(max_length=20, blank=True, null=True)
    followup_private = models.IntegerField(blank=True, null=True)
    task_private = models.IntegerField(blank=True, null=True)
    default_requesttypes_id = models.PositiveIntegerField(blank=True, null=True)
    password_forget_token = models.CharField(max_length=40, blank=True, null=True)
    password_forget_token_date = models.DateTimeField(blank=True, null=True)
    user_dn = models.TextField(blank=True, null=True)
    user_dn_hash = models.CharField(max_length=32, blank=True, null=True)
    registration_number = models.CharField(max_length=255, blank=True, null=True)
    show_count_on_tabs = models.IntegerField(blank=True, null=True)
    refresh_views = models.IntegerField(blank=True, null=True)
    set_default_tech = models.IntegerField(blank=True, null=True)
    personal_token = models.CharField(max_length=255, blank=True, null=True)
    personal_token_date = models.DateTimeField(blank=True, null=True)
    api_token = models.CharField(max_length=255, blank=True, null=True)
    api_token_date = models.DateTimeField(blank=True, null=True)
    cookie_token = models.CharField(max_length=255, blank=True, null=True)
    cookie_token_date = models.DateTimeField(blank=True, null=True)
    display_count_on_home = models.IntegerField(blank=True, null=True)
    notification_to_myself = models.IntegerField(blank=True, null=True)
    duedateok_color = models.CharField(max_length=255, blank=True, null=True)
    duedatewarning_color = models.CharField(max_length=255, blank=True, null=True)
    duedatecritical_color = models.CharField(max_length=255, blank=True, null=True)
    duedatewarning_less = models.IntegerField(blank=True, null=True)
    duedatecritical_less = models.IntegerField(blank=True, null=True)
    duedatewarning_unit = models.CharField(max_length=255, blank=True, null=True)
    duedatecritical_unit = models.CharField(max_length=255, blank=True, null=True)
    is_deleted_ldap = models.IntegerField()
    pdffont = models.CharField(max_length=255, blank=True, null=True)
    picture = models.CharField(max_length=255, blank=True, null=True)
    begin_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    keep_devices_when_purging_item = models.IntegerField(blank=True, null=True)
    privatebookmarkorder = models.TextField(blank=True, null=True)
    backcreated = models.IntegerField(blank=True, null=True)
    task_state = models.IntegerField(blank=True, null=True)
    palette = models.CharField(max_length=20, blank=True, null=True)
    page_layout = models.CharField(max_length=20, blank=True, null=True)
    fold_menu = models.IntegerField(blank=True, null=True)
    savedsearches_pinned = models.TextField(blank=True, null=True)
    timeline_order = models.CharField(max_length=20, blank=True, null=True)
    itil_layout = models.TextField(blank=True, null=True)
    richtext_layout = models.CharField(max_length=20, blank=True, null=True)
    set_default_requester = models.IntegerField(blank=True, null=True)
    lock_autolock_mode = models.IntegerField(blank=True, null=True)
    lock_directunlock_notification = models.IntegerField(blank=True, null=True)
    date_creation = models.DateTimeField(blank=True, null=True)
    highcontrast_css = models.IntegerField(blank=True, null=True)
    plannings = models.TextField(blank=True, null=True)
    sync_field = models.CharField(max_length=255, blank=True, null=True)
    groups_id = models.PositiveIntegerField()
    users_id_supervisor = models.PositiveIntegerField()
    timezone = models.CharField(max_length=50, blank=True, null=True)
    default_dashboard_central = models.CharField(max_length=100, blank=True, null=True)
    default_dashboard_assets = models.CharField(max_length=100, blank=True, null=True)
    default_dashboard_helpdesk = models.CharField(max_length=100, blank=True, null=True)
    default_dashboard_mini_ticket = models.CharField(max_length=100, blank=True, null=True)
    default_central_tab = models.IntegerField(blank=True, null=True)
    nickname = models.CharField(max_length=255, blank=True, null=True)
    substitution_start_date = models.DateTimeField(blank=True, null=True)
    substitution_end_date = models.DateTimeField(blank=True, null=True)
    timeline_action_btn_layout = models.IntegerField(blank=True, null=True)
    timeline_date_format = models.IntegerField(blank=True, null=True)
    toast_location = models.CharField(max_length=255, blank=True, null=True)
    set_followup_tech = models.IntegerField(blank=True, null=True)
    set_solution_tech = models.IntegerField(blank=True, null=True)
    planned_task_state = models.IntegerField(blank=True, null=True)
    number_2fa = models.TextField(db_column='2fa', blank=True, null=True)  # Field renamed because it wasn't a valid Python identifier.
    number_2fa_unenforced = models.IntegerField(db_column='2fa_unenforced')  # Field renamed because it wasn't a valid Python identifier.
    password_history = models.TextField(blank=True, null=True)
    is_notif_enable_default = models.IntegerField(blank=True, null=True)
    show_search_form = models.IntegerField(blank=True, null=True)
    search_pagination_on_top = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'glpi_users'
        unique_together = (('name', 'authtype', 'auths_id'),)
