---

name: 'Python'


on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:


  python-build:
    name: 'Build'
    if: "!startsWith(github.ref, 'refs/tags/')"
    uses: nofusscomputing/action_python/.github/workflows/python-package.yaml@development

  python-build_tag:
    name: 'Build'
    if: startsWith(github.ref, 'refs/tags/')
    uses: nofusscomputing/action_python/.github/workflows/python-package.yaml@development

  #
  # See: https://github.com/pypa/gh-action-pypi-publish/issues/166
  # See: https://github.com/pypi/warehouse/issues/11096
  # python-publish:
  #   name: 'Python Build'
  #   uses: nofusscomputing/action_python/.github/workflows/python-publish.yaml@development
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs:
  #     - python-build
  #   with:
  #     PYTHON_PROJECT_NAME: 
  #   secrets:
  #     password: ${{ secrets.NFC_PYPI_TOKEN }}


  python-publish:
    name: 'Publish'
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/glpi-import/
    permissions:
      id-token: write
    needs:
      - python-build_tag
    
    steps:

      - name: Download built artifact to dist/
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist


      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
